package com.monolito365.model;
// Generated 30/08/2021 10:24:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer id;
     private TipoDocumentos tipoDocumentos;
     private Usuarios usuarios;
     private String nombres;
     private String apellidos;
     private String direccion;
     private String telefono1;
     private String telefono2;
     private String email;
     private String paginaWeb;
     private String numeroDoc;
     private Date fechaRegistro;
     private Date fechaModificacion;

     public Clientes() {
        //cargan objetos relacionados, se agrega manualmente
        this.usuarios = new Usuarios();
        this.tipoDocumentos = new TipoDocumentos();
    }
	
    public Clientes(TipoDocumentos tipoDocumentos,Usuarios usuarios, String nombres, String direccion, String telefono1, String email, String numeroDoc, Date fechaRegistro) {
        this.tipoDocumentos = tipoDocumentos;
        this.usuarios = usuarios;
        this.nombres = nombres;
        this.direccion = direccion;
        this.telefono1 = telefono1;
        this.email = email;
        this.numeroDoc = numeroDoc;
        this.fechaRegistro = fechaRegistro;
    }
    public Clientes(TipoDocumentos tipoDocumentos, Usuarios usuarios, String nombres, String apellidos, String direccion, String telefono1, String telefono2, String email, String paginaWeb, String numeroDoc, Date fechaRegistro, Date fechaModificacion) {
       this.tipoDocumentos = tipoDocumentos;
       this.usuarios = usuarios;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.email = email;
       this.paginaWeb = paginaWeb;
       this.numeroDoc = numeroDoc;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TipoDocumentos getTipoDocumentos() {
        return this.tipoDocumentos;
    }
    
    public void setTipoDocumentos(TipoDocumentos tipoDocumentos) {
        this.tipoDocumentos = tipoDocumentos;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public String getNumeroDoc() {
        return this.numeroDoc;
    }
    
    public void setNumeroDoc(String numeroDoc) {
        this.numeroDoc = numeroDoc;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }


}


