package com.monolito365.model;
// Generated 30/08/2021 10:24:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyectos generated by hbm2java
 */
public class Proyectos  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuarios;
     private String proyecto;
     private String descripcion;
     private boolean estado;
     private Date fechaExpiracion;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set<ArchivosProyectos> archivosProyectoses = new HashSet<ArchivosProyectos>(0);

    public Proyectos() {
        //instancias necesarias, se agrega manualmente
        usuarios = new Usuarios();
    }

	
    public Proyectos(Usuarios usuarios, String proyecto, String descripcion, boolean estado, Date fechaExpiracion, Date fechaRegistro) {
        this.usuarios = usuarios;
        this.proyecto = proyecto;
        this.descripcion = descripcion;
        this.estado = estado;
        this.fechaExpiracion = fechaExpiracion;
        this.fechaRegistro = fechaRegistro;
    }
    public Proyectos(Usuarios usuarios, String proyecto, String descripcion, boolean estado, Date fechaExpiracion, Date fechaRegistro, Date fechaModificacion, Set<ArchivosProyectos> archivosProyectoses) {
       this.usuarios = usuarios;
       this.proyecto = proyecto;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaExpiracion = fechaExpiracion;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.archivosProyectoses = archivosProyectoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(String proyecto) {
        this.proyecto = proyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<ArchivosProyectos> getArchivosProyectoses() {
        return this.archivosProyectoses;
    }
    
    public void setArchivosProyectoses(Set<ArchivosProyectos> archivosProyectoses) {
        this.archivosProyectoses = archivosProyectoses;
    }




}


