package com.monolito365.model;
// Generated 30/08/2021 10:24:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumentos generated by hbm2java
 */
public class TipoDocumentos  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

    public TipoDocumentos() {
    }

	
    public TipoDocumentos(String descripcion, Date fechaRegistro) {
        this.descripcion = descripcion;
        this.fechaRegistro = fechaRegistro;
    }
    public TipoDocumentos(String descripcion, Date fechaRegistro, Date fechaModificacion, Set<Clientes> clienteses) {
       this.descripcion = descripcion;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.clienteses = clienteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }




}


