package com.monolito365.model;
// Generated 30/08/2021 10:24:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private Roles roles;
     private String username;
     private String password;
     private boolean estado;
     private Date fechaRegistro;
     private Date fechaModificacion;
     private Set<Proyectos> proyectoses = new HashSet<Proyectos>(0);
     private Set<Clientes> clienteses = new HashSet<Clientes>(0);

   public Usuarios() {
        // se agrega manualmente
        roles = new Roles();
    }
	
    public Usuarios(Roles roles, String username, String password, boolean estado, Date fechaRegistro) {
        this.roles = roles;
        this.username = username;
        this.password = password;
        this.estado = estado;
        this.fechaRegistro = fechaRegistro;
    }
    public Usuarios(Roles roles, String username, String password, boolean estado, Date fechaRegistro, Date fechaModificacion, Set<Proyectos> proyectoses, Set<Clientes> clienteses) {
       this.roles = roles;
       this.username = username;
       this.password = password;
       this.estado = estado;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
       this.proyectoses = proyectoses;
       this.clienteses = clienteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set<Proyectos> getProyectoses() {
        return this.proyectoses;
    }
    
    public void setProyectoses(Set<Proyectos> proyectoses) {
        this.proyectoses = proyectoses;
    }
    public Set<Clientes> getClienteses() {
        return this.clienteses;
    }
    
    public void setClienteses(Set<Clientes> clienteses) {
        this.clienteses = clienteses;
    }





}


